name: delu
channels:
- https://conda.anaconda.org/conda-forge
- nodefaults
dependencies:
# Package.
- numpy=1.19.5
- python=3.8.17
- pytorch=1.8.0
# Documentation.
- furo=2023.9.10
- pdoc=14.1.0
- sphinx=7.1.2
- sphinx-copybutton=0.5.2
- sphinx-remove-toctrees=0.0.3
- sphinxcontrib-spelling==8.0.0
# Development.
- black=23.9.1
- coverage=7.3.1
- flit=3.9.0
- isort=5.12.0
- mypy=1.5.1
- pre-commit-hooks=4.4.0
- pytest=7.4.2
- ruff=0.0.292
- xdoctest=1.1.1
# Other
- jupyterlab=4.0.6
- pip:
  # Documentation.
  - sphinxcontrib-spelling==8.0.0
